config_version = 11

[backdrop]
blur_intensity = 0.0
enabled = true
tint_intensity = 0.099999997764825821

[bar.default]
background_opacity = 0.33999999240040779
capsule = true
capsule_opacity = 0.4999999888241291
capsule_padding = 8.0
capsule_thickness = 0.99999998137354851
end = [ "tray", "network", "bluetooth", "volume", "brightness", "battery", "control-center" ]
margin_ends = 0
scale = 0.7500000037252903
start = [ "launcher", "workspaces", "group:g1", "media" ]
thickness = 28

    [bar.default.dead_zone.actions]
    middle = "media toggle"

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "cpu", "ram", "temp", "sysmon", "network_rx", "network_tx" ]
    opacity = 0.5
    padding = 6.0

[battery]
warning_threshold = 15

[control_center.calendar]
show_week_numbers = true

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "nightlight"

[desktop_widgets]
enabled = true
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000006",
    "desktop-widget-0000000000000007",
    "desktop-widget-github-prs",
    "desktop-widget-github-issues"
]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 144.0
    box_width = 336.0
    cx = 1704.0
    cy = 948.0
    output = "HDMI-A-1"
    rotation = -0.0
    type = "media_player"

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    box_height = 96.0
    box_width = 512.0
    cx = 960.0
    cy = 812.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        bands = 32
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000007]
    box_height = 132.33984375
    box_width = 689.95703125
    cx = 960.0
    cy = 238.169921875
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000007.settings]
        background_opacity = 0.0
        center_text = true
        clock_style = "digital"
        format = "{:%H:%M:%S}"
        timezone = "UTC"

    [desktop_widgets.widget.desktop-widget-github-issues]
    box_height = 440.0
    box_width = 0.0
    cx = 296.0
    cy = 772.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "prnsh/github:list"

        [desktop_widgets.widget.desktop-widget-github-issues.settings]
        author = "everyone"
        background_padding = 32
        cap = 50
        kind = "issues"

    [desktop_widgets.widget.desktop-widget-github-prs]
    box_height = 440.0
    box_width = 0.0
    cx = 298.0
    cy = 292.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "prnsh/github:list"

        [desktop_widgets.widget.desktop-widget-github-prs.settings]
        author = "everyone"
        background_padding = 32
        cap = 50
        kind = "prs"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 1

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 300.0

[location]
address = "chennai"

[lockscreen]
blur_intensity = 0.0
tint_intensity = 0.099999997764825821

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-1",
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000006",
    "lockscreen-widget-0000000000000007",
    "lockscreen-widget-0000000000000008",
    "lockscreen-widget-0000000000000009"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 528.0
    cx = 960.0
    cy = 1007.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.5
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 960.0
    cy = 982.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "on_primary"
        background_opacity = 0.75
        background_radius = 12.0
        center_password_text = true
        input_opacity = 0.95000000000000007
        input_radius = 8.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = false
        show_login_button = false
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 208.0
    box_width = 720.0
    cx = 960.0
    cy = 208.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 80.0
    box_width = 496.0
    cx = 960.0
    cy = 720.0
    output = "eDP-1"
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        bands = 32
        show_when_idle = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 160.0
    box_width = 400.0
    cx = 224.0
    cy = 984.0
    output = "eDP-1"
    rotation = 0.0
    type = "media_player"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 32.0
    box_width = 32.0
    cx = 1824.0
    cy = 60.0
    output = "eDP-1"
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = true
        command = "noctalia msg session shutdown"
        glyph = "shutdown"
        variant = "primary"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 32.0
    box_width = 32.0
    cx = 1776.0
    cy = 60.0
    output = "eDP-1"
    rotation = -0.0
    type = "button"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        background = true
        command = "noctalia msg session reboot"
        glyph = "reboot"
        label = ""
        variant = "default"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000006]
    box_height = 32.0
    box_width = 32.0
    cx = 1728.0
    cy = 60.0
    output = "eDP-1"
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000006.settings]
        background = true
        command = "noctalia msg session suspend"
        glyph = "zzz"
        label = ""
        variant = "default"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
    box_height = 96.0
    box_width = 592.0
    cx = 960.0
    cy = 796.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000007.settings]
        bands = 32
        show_when_idle = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000008]
    box_height = 160.0
    box_width = 592.0
    cx = 960.0
    cy = 236.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000008.settings]
        background_opacity = 0.0
        format = "{:%H:%M:%S}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000009]
    box_height = 0.0
    box_width = 0.0
    cx = 195.0
    cy = 946.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "media_player"

[notification]
background_opacity = 0.89999997988343239
history_retention_hours = 12
layer = "overlay"
position = "top_center"
scale = 0.80000000447034836

[osd]
background_opacity = 0.89999997988343239
position = "top_center"
scale = 0.80000000447034836

[plugins]
enabled = [ "prnsh/github" ]

[shell]
app_icon_colorize = false
avatar_path = "/home/prnsh/Pictures/Wallpapers/avatars/icarus.png"
clipboard_auto_paste = "ctrl_v"
clipboard_history_max_entries = 1000
corner_radius_scale = 1.2500000186264515
show_location = false

    [shell.animation]
    speed = 1.2500000186264515

    [shell.launcher]
    app_grid = true

        [shell.launcher.providers.emoji]
        global = false

    [shell.panel]
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"
    transparency_mode = "soft"

    [shell.shadow]
    direction = "center"

[theme]
community_palette = "Oxocarbon"
mode = "dark"
pure_black_dark = true
wallpaper_scheme = "m3-monochrome"

    [theme.templates]
    community_ids = [ "neovim", "obsidian", "discord", "prismlauncher", "steam" ]
    enable_builtin_templates = false

[wallpaper.default]
path = "/home/prnsh/Pictures/Wallpapers/wallhaven-d8om6o.jpg"

[wallpaper.last]
path = "/home/prnsh/Pictures/Wallpapers/wallhaven-d8om6o.jpg"

[wallpaper.monitors.HDMI-A-1]
path = "/home/prnsh/Pictures/Wallpapers/wallhaven-d8om6o.jpg"

[wallpaper.monitors.eDP-1]
path = "/home/prnsh/Pictures/Wallpapers/wallhaven-d8om6o.jpg"

[[wallpaper.favorite]]
palette_source = "wallpaper"
path = "/home/prnsh/Pictures/Wallpapers/gengar.jpg"
theme_mode = "dark"
wallpaper_scheme = "m3-monochrome"

[[wallpaper.favorite]]
palette_source = "wallpaper"
path = "/home/prnsh/Pictures/Wallpapers/hero-landscape.webp"
theme_mode = "dark"
wallpaper_scheme = "m3-monochrome"

[[wallpaper.favorite]]
palette_source = "wallpaper"
path = "/home/prnsh/Pictures/Wallpapers/image.png"
theme_mode = "dark"
wallpaper_scheme = "m3-monochrome"

[widget.bluetooth]
show_label = true

[widget.clock]
capsule = true
capsule_opacity = 0.65000000000000002
capsule_padding = 12
format = "{:%H:%M:%S} {:%d-%m-%Y}"

[widget.control-center]
glyph = "bolt-filled"

[widget.cpu]
show_label = false

[widget.launcher]
enabled = false

[widget.media]
hide_when_no_media = true
max_length = 200
min_length = 200
title_scroll = "always"

[widget.network_tx]
enabled = false

[widget.ram]
show_label = false

[widget.sysmon]
enabled = false
show_value = true
stat = "disk_pct"

[widget.temp]
show_label = false

[widget.workspaces]
active_pill_size = 3.0